from enum import Enum


class TokenType(Enum):
    ID = 'ID'
    INTEGER_LITERAL = 'INTEGER_LITERAL'
    FLOAT_LITERAL = 'FLOAT_LITERAL'
    STRING_LITERAL = 'STRING_LITERAL'
    CHAR_LITERAL = 'CHAR_LITERAL'
    ARRAY = 'ARRAY'
    AUTO = 'AUTO'
    BOOLEAN = 'BOOLEAN'
    CHAR = 'CHAR'
    ELSE = 'ELSE'
    FALSE = 'FALSE'
    FLOAT = 'FLOAT'
    FOR = 'FOR'
    FUNCTION = 'FUNCTION'
    IF = 'IF'
    INTEGER = 'INTEGER'
    PRINT = 'PRINT'
    RETURN = 'RETURN'
    STRING = 'STRING'
    TRUE = 'TRUE'
    VOID = 'VOID'
    WHILE = 'WHILE'
    DO = 'DO'


class OperatorType(Enum):
    LT = 'LT'
    LE = 'LE'
    GT = 'GT'
    GE = 'GE'
    EQ = 'EQ'
    NE = 'NE'
    LAND = 'LAND'
    LOR = 'LOR'
    INC = 'INC'
    DEC = 'DEC'


class LiteralType(Enum):
    PLUS = '+'
    MINUS = '-'
    STAR = '*'
    SLASH = '/'
    PERCENT = '%'
    CARET = '^'
    EQUAL = '='
    LPAREN = '('
    RPAREN = ')'
    LBRACKET = '['
    RBRACKET = ']'
    LBRACE = '{'
    RBRACE = '}'
    COLON = ':'
    COMMA = ','
    SEMICOLON = ';'
    BANG = '!'
